#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
#include <libgen.h>

const char *shift(int *argc, char ***argv) {
    (*argc)--;
    return *(*argv)++;
}

void usage(const char *program) {
    printf("Usage: %s [-o <output filename|->] [[--name <variable name>] <filename>]*\n", program);
}

void close_sink(FILE* sink) {
    if (sink != stderr) fclose(sink);
}

bool file_exists(const char *filename) {
    FILE *f = fopen(filename, "rb");
    if (f == NULL) return false;
    fclose(f);
    return true;
}

const char *generate_name(const char *next_name, const char *arg) {
  const char *origin = basename((char*) arg);
    if (next_name) origin = next_name;
    static char name[64];
    int length = strlen(origin) > 63 ? 63 : strlen(origin);
    int i = 0;
    for (; i < length; i++) {
        char charachter = origin[i];
        if (isalpha(charachter)) name[i] = toupper(charachter);
        else if (isdigit(charachter)) name[i] = charachter;
        else name[i] = '_';
    }
    name[i] = 0;
    return name;
}

int main(int argc, char **argv) {
    const char *program = shift(&argc, &argv);

    if (!argc) {
        usage(program);
        return 1;
    }

    FILE *sink = stderr;
    const char *next_name = NULL;

    int files_bundled = 0;
    const char files[128][64];
    
    while (argc) {
        const char *arg = shift(&argc, &argv);
        if (strcmp(arg, "-o") == 0) {
            close_sink(sink);
            if (argc == 0) {
                usage(program); return 1;
            }
            const char *output = shift(&argc, &argv);
            if (strcmp(output, "-") == 0) sink = stderr;
            else sink = fopen(output, "wb");
        } else if (strcmp(arg, "--name") == 0) {
            if (argc == 0) {
                close_sink(sink); usage(program); return 1;
            }
            next_name = shift(&argc, &argv);
        } else {
            if (!file_exists(arg)) {
                close_sink(sink); usage(program); return 1;
            }
            FILE *file = fopen(arg, "rb");
            if (file == NULL) continue;
            fseek(file, 0, SEEK_END);
            size_t size = ftell(file);
            fseek(file, 0, SEEK_SET);

            const char *name = generate_name(next_name, arg);

            fprintf(sink, "\nconst unsigned long long _%s_LENGTH = %zu;\nconst unsigned char _%s[] = {\n", name, size, name);

            while (!feof(file) && !ferror(file)) {
                char bytes[16];
                int bytes_read = fread(bytes, 1, 16, file);
                fprintf(sink, "    ");
                for (int i = 0; i < bytes_read; i++) {
                    fprintf(sink, "0x%02X, ", bytes[i] & 0xFF);
                }
                fprintf(sink, "\n");
            }

            fprintf(sink, "};\n");
            
            fclose(file);

            memcpy((void*) files[files_bundled++], name, strlen(name) + 1);
            next_name = NULL;
            
            printf("Bundled file %s\n", arg);
        }
    }

    fprintf(sink, "\n/*\n * This file was auto-generated by mus3 bundler.\n * Files bundled: ");
    for (int i = 0; i < files_bundled; i++) {
        fprintf(sink, "_%s", files[i]);
        if (i < files_bundled - 1) fprintf(sink, ", ");
    }
    fprintf(sink, " (%d files overall)\n */\n", files_bundled);
    
    return 0;
}
